#!/bin/sh

#  HeatWave_Analysis.sh
#  
#
#  Created by Edmondo Di Giuseppe on 18/11/15.
#
#
# Based on 2 files generated by CDO.HeatWave-generator.sh: 
# *_Begin_HeatWave.nc; 
# *_Duration_HeatWave.nc
# già settati per il tempo e applicata la mask per il mare
#
# 1) seleziona i mesi su cui si vuole l'analisi
# 2) seleziona i bacini del Med sui quali effettuare l'analisi
# 3) dal file *Duration* crea un file .nc che estende gli uno a tutti i giorni dell'ondata
# 4) resetta il time sul file creato al punto 3)
# 5) Crea Medie(Somme) Mensili e grafici
#####################################################################################

# Select season:
months="1,2,3,4,5,6,7,8,9,10,11,12"       

#Input bounds box coordinates for interested area:
Zone1="-14,24,30,50"     #Western+Central Med

for var in tx tn
do
	for i in Begin Duration 
  do

		index=1
		for Zone in $Zone1 
		do
  		#####
		  # METTERE I FILES DENTRO la dir: Data
      cdo selmon,$months -sellonlatbox,$Zone Data/"$var"_ECAD_"$i"_HeatWave3.nc Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc        

      if [ "$i" = "Duration" ] 
      then
         echo ".......R: crea file .nc con tutti 1"
         /usr/bin/R --slave -f Write1ToDurationDays.R
         echo ".......R: prodotto file .nc con tutti 1"
         ## Reset of time axis in the output file *Extended.nc:
         ncrename -O -v z,time -d z,time Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index"_Extended0.nc Data/Appo.nc
         cdo settaxis,1951-01-01,12:00:00,1day -setcalendar,standard -settunits,day Data/Appo.nc Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index"_Extended.nc
         
         #Monthly averages:
         cdo -O monmean -setctomiss,0 Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc Data/MM_"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc
         cdo -O monmax  -setctomiss,0 Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc Data/MX_"$var"_ECAD_"$i"Max_HeatWave_Cut"$index".nc
      else
         cdo -O monsum -setctomiss,0 Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc Data/MM_"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc
		  fi

		  index=$((index+1))       #incremento l'etichetta per il nome dei files
		  done
                
	done
done

#Plots con script di R
#
echo "........... partono i plot R"
#               /usr/bin/R --slave -f HeatWaveDurationPlots.R
#               echo "........... 1"
/usr/bin/R --slave -f HotDaysPlots.R
echo "........... 2" 
echo "............... finiti!"
        	
rm -f  Data/Appo.nc

