#!/bin/sh

#  HeatWave_Analysis.sh
#  
#
#  Created by Edmondo Di Giuseppe on 18/11/15.
#
#
# Based on 2 files generated by CDO.HeatWave-generator.sh: 
# *_Begin_HeatWave.nc; 
# *_Duration_HeatWave.nc
# già settati per il tempo e applicata la mask per il mare
#
# 1) seleziona i mesi su cui si vuole l'analisi
# 2) seleziona i 3 bacini del Med sui quali effettuare l'analisi
#####################################################################################

# Select season:
months="1,2,3,4,5,6,7,8,9,10,11,12"       #example for may-sept

#Input bounds box coordinates for interested area:
Zone1="-14,24,30,50"     #Western+Central Med

# Reset della variabile tempo nei files prodotti da R/selezione mesi iMag-Sept:
for var in tx tn
do
	for i in Begin Duration #MonthCrossing
     	do

		index=1
		for Zone in $Zone1 
		do
		#####
		# METTERE I FILES DENTRO la dir: Data
                cdo selmon,$months -sellonlatbox,$Zone ../marrakech/Data/"$var"_ECAD_"$i"_HeatWave3.nc Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc        
#		echo selmon,$months -sellonlatbox,$Zone ../marrakech/Data/"$var"_ECAD_"$i"_HeatWave3../marrakech/Data/.nc Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc

                if [ "$i" = "Duration" ] 
                then
                       cdo -O monmean -setctomiss,0 Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc Data/MM_"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc
                       cdo -O monmax  -setctomiss,0 Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc Data/MX_"$var"_ECAD_"$i"Max_HeatWave_Cut"$index".nc
                else
                       cdo -O monsum -setctomiss,0 Data/"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc Data/MM_"$var"_ECAD_"$i"_HeatWave_Cut"$index".nc
		fi

		index=$((index+1))       #incremento l'etichetta per il nome dei files
		done
                
	done
done

#Plots con script di R
# Aggiunti il 6.11.2015
                #
echo "........... partono i plot R"
#               /usr/bin/R --slave -f HeatWaveDurationPlots.R
#               echo "........... 1"
/usr/bin/R --slave -f HotDaysPlots.R
echo "........... 2" 
echo "............... finiti!"
        	

